name: speaksigns
description: "A new Flutter project."
publish_to: 'none'
version: 2.12.0


environment:
  sdk: ^3.7.2

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core:
  firebase_auth:
  firebase_storage:
  firebase_app_check:
  firebase_ml_model_downloader:
  webview_flutter:
  lottie:

  image_picker:
  video_player:
  tflite_flutter:

  permission_handler:
  camera:
  url_launcher:
  telephony:
  http:
  android_intent_plus:
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animation/
    - assets/images/
    - assets/videos/
    - assets/tfmodel/

flutter_launcher_icons:
  android: true


  image_path: "assets/images/Logo.png"

